from __future__ import annotations
import json
import math
from dataclasses import asdict, dataclass, field, is_dataclass
from pathlib import Path
from typing import Any, Dict, List, Literal, Mapping, Optional, Sequence


ActionName = Literal["SearchGraph", "SubmitFinalAnswer"]


def _to_plain(value: Any) -> Any:
    if value is None:
        return None

    if is_dataclass(value):
        return {key: _to_plain(item) for key, item in asdict(value).items()}

    if isinstance(value, Mapping):
        return {str(key): _to_plain(item) for key, item in value.items()}

    if isinstance(value, (list, tuple)):
        return [_to_plain(item) for item in value]

    if isinstance(value, (str, int, float, bool)):
        return value

    if hasattr(value, "__dict__"):
        return {
            str(key): _to_plain(item)
            for key, item in vars(value).items()
            if not str(key).startswith("_")
        }

    return str(value)


def _ensure_finite(value: float, name: str) -> None:
    if not math.isfinite(float(value)):
        raise ValueError(f"{name} must be finite, got {value!r}.")


def _validate_binary_mask(mask: Sequence[int], name: str) -> None:
    invalid = [value for value in mask if int(value) not in (0, 1)]
    if invalid:
        raise ValueError(f"{name} must contain only 0/1 values; found {invalid[:5]!r}.")


@dataclass
class GoldSupportingPassage:
    title: str = ""
    text: str = ""
    passage_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if not self.title.strip() and not self.text.strip():
            raise ValueError(
                "GoldSupportingPassage must contain at least a non-empty title or text."
            )

    def to_dict(self) -> Dict[str, Any]:
        self.validate()
        return _to_plain(self)


@dataclass
class TrajectoryReward:
    components: Dict[str, float] = field(default_factory=dict)
    weights: Dict[str, float] = field(default_factory=dict)
    total: float = 0.0

    def recompute_total(self) -> float:
        total = 0.0
        for name, value in self.components.items():
            weight = self.weights.get(name, 1.0)
            _ensure_finite(float(value), f"reward component {name!r}")
            _ensure_finite(float(weight), f"reward weight {name!r}")
            total += float(weight) * float(value)

        self.total = float(total)
        return self.total

    def validate(self) -> None:
        for name, value in self.components.items():
            _ensure_finite(float(value), f"reward component {name!r}")

        for name, value in self.weights.items():
            _ensure_finite(float(value), f"reward weight {name!r}")

        _ensure_finite(float(self.total), "reward total")

    def to_dict(self) -> Dict[str, Any]:
        self.validate()
        return _to_plain(self)


@dataclass
class RolloutAction:
    step_id: int
    prompt_messages: List[Dict[str, str]]
    prompt_text: str
    # Exact controller prefix used for generation.
    prompt_input_ids: List[int]
    prompt_attention_mask: List[int] = field(default_factory=list)
    # Only tokens generated by the trainable 8B controller.
    generated_text: str = ""
    generated_token_ids: List[int] = field(default_factory=list)
    old_log_probs: List[float] = field(default_factory=list)
    action_token_mask: List[int] = field(default_factory=list)
    # Parsed action and execution diagnostics.
    action_name: Optional[ActionName] = None
    parsed_action: Dict[str, Any] = field(default_factory=dict)
    parse_success: bool = False
    fallback_used: bool = False
    forced_stop: bool = False
    # Frozen-environment feedback. These tokens never receive policy loss.
    observation_text: str = ""
    observation_payload: Optional[Dict[str, Any]] = None
    observation_token_ids: List[int] = field(default_factory=list)
    generation_metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.prompt_input_ids and not self.prompt_attention_mask:
            self.prompt_attention_mask = [1] * len(self.prompt_input_ids)

        if self.generated_token_ids and not self.action_token_mask:
            self.action_token_mask = [1] * len(self.generated_token_ids)

    @property
    def num_prompt_tokens(self) -> int:
        return len(self.prompt_input_ids)

    @property
    def num_action_tokens(self) -> int:
        return int(sum(self.action_token_mask))

    @property
    def num_observation_tokens(self) -> int:
        return len(self.observation_token_ids)

    def validate(self, require_old_log_probs: bool = False) -> None:
        if self.step_id < 0:
            raise ValueError(f"step_id must be >= 0, got {self.step_id}.")

        if not isinstance(self.prompt_messages, list):
            raise TypeError("prompt_messages must be a list of role/content dictionaries.")

        for index, message in enumerate(self.prompt_messages):
            if not isinstance(message, dict):
                raise TypeError(f"prompt_messages[{index}] must be a dictionary.")
            if "role" not in message or "content" not in message:
                raise ValueError(
                    f"prompt_messages[{index}] must contain 'role' and 'content'."
                )

        if len(self.prompt_attention_mask) != len(self.prompt_input_ids):
            raise ValueError(
                "prompt_attention_mask length must equal prompt_input_ids length: "
                f"{len(self.prompt_attention_mask)} != {len(self.prompt_input_ids)}."
            )
        _validate_binary_mask(self.prompt_attention_mask, "prompt_attention_mask")

        if len(self.action_token_mask) != len(self.generated_token_ids):
            raise ValueError(
                "action_token_mask length must equal generated_token_ids length: "
                f"{len(self.action_token_mask)} != {len(self.generated_token_ids)}."
            )
        _validate_binary_mask(self.action_token_mask, "action_token_mask")

        if self.old_log_probs:
            if len(self.old_log_probs) != len(self.generated_token_ids):
                raise ValueError(
                    "old_log_probs length must equal generated_token_ids length: "
                    f"{len(self.old_log_probs)} != {len(self.generated_token_ids)}."
                )
            for index, value in enumerate(self.old_log_probs):
                _ensure_finite(float(value), f"old_log_probs[{index}]")
        elif require_old_log_probs and self.generated_token_ids:
            raise ValueError(
                "old_log_probs are required for a sampled action but are missing."
            )

        if self.action_name is not None and self.action_name not in (
            "SearchGraph",
            "SubmitFinalAnswer",
        ):
            raise ValueError(f"Unsupported action_name: {self.action_name!r}.")

        if self.parse_success and self.action_name is None:
            raise ValueError(
                "parse_success=True requires action_name to be populated."
            )

    def to_dict(self) -> Dict[str, Any]:
        self.validate(require_old_log_probs=False)
        return _to_plain(self)


@dataclass
class PolicyStepSample:
    trajectory_id: str
    question_id: str
    group_index: int
    step_id: int
    prompt_input_ids: List[int]
    prompt_attention_mask: List[int]
    target_token_ids: List[int]
    target_token_mask: List[int]
    old_log_probs: List[float]
    advantage: float
    trajectory_reward: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if len(self.prompt_input_ids) != len(self.prompt_attention_mask):
            raise ValueError(
                "prompt_input_ids and prompt_attention_mask must have equal length."
            )
        _validate_binary_mask(self.prompt_attention_mask, "prompt_attention_mask")

        if len(self.target_token_ids) != len(self.target_token_mask):
            raise ValueError(
                "target_token_ids and target_token_mask must have equal length."
            )
        _validate_binary_mask(self.target_token_mask, "target_token_mask")

        if len(self.old_log_probs) != len(self.target_token_ids):
            raise ValueError(
                "old_log_probs and target_token_ids must have equal length."
            )

        for index, value in enumerate(self.old_log_probs):
            _ensure_finite(float(value), f"old_log_probs[{index}]")

        _ensure_finite(float(self.advantage), "advantage")
        _ensure_finite(float(self.trajectory_reward), "trajectory_reward")

    def to_dict(self) -> Dict[str, Any]:
        self.validate()
        return _to_plain(self)


@dataclass
class RolloutTrajectory:
    trajectory_id: str
    question_id: str
    question: str
    group_index: int

    gold_answers: List[str] = field(default_factory=list)
    gold_supporting_passages: List[GoldSupportingPassage] = field(
        default_factory=list
    )

    actions: List[RolloutAction] = field(default_factory=list)

    controller_final_answer: Optional[str] = None
    reader_predicted_answer: Optional[str] = None

    base_evidence_passages: List[Dict[str, Any]] = field(default_factory=list)
    selected_evidence_passages: List[Dict[str, Any]] = field(default_factory=list)
    fused_evidence_passages: List[Dict[str, Any]] = field(default_factory=list)
    filtered_triples: List[Dict[str, Any]] = field(default_factory=list)

    reader_supporting_passage_ids: List[str] = field(default_factory=list)
    reader_supporting_triples: List[str] = field(default_factory=list)

    num_search_calls: int = 0
    termination_reason: Optional[str] = None
    forced_stop: bool = False

    reward: TrajectoryReward = field(default_factory=TrajectoryReward)
    advantage: Optional[float] = None

    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def num_steps(self) -> int:
        return len(self.actions)

    @property
    def num_policy_tokens(self) -> int:
        return sum(action.num_action_tokens for action in self.actions)

    @property
    def predicted_answer(self) -> str:
        reader_answer = (self.reader_predicted_answer or "").strip()
        if reader_answer:
            return reader_answer
        return (self.controller_final_answer or "").strip()

    def add_action(self, action: RolloutAction) -> None:
        expected_step_id = len(self.actions)
        if action.step_id != expected_step_id:
            raise ValueError(
                f"Expected step_id={expected_step_id}, got {action.step_id}."
            )
        self.actions.append(action)

    def validate(self, require_old_log_probs: bool = False) -> None:
        if not self.trajectory_id.strip():
            raise ValueError("trajectory_id must be non-empty.")
        if not self.question_id.strip():
            raise ValueError("question_id must be non-empty.")
        if not self.question.strip():
            raise ValueError("question must be non-empty.")
        if self.group_index < 0:
            raise ValueError("group_index must be >= 0.")
        if self.num_search_calls < 0:
            raise ValueError("num_search_calls must be >= 0.")

        for index, support in enumerate(self.gold_supporting_passages):
            try:
                support.validate()
            except Exception as exc:
                raise ValueError(
                    f"Invalid gold_supporting_passages[{index}]: {exc}"
                ) from exc

        for index, action in enumerate(self.actions):
            if action.step_id != index:
                raise ValueError(
                    "Action step IDs must be contiguous and start at zero: "
                    f"actions[{index}].step_id={action.step_id}."
                )
            action.validate(require_old_log_probs=require_old_log_probs)

        self.reward.validate()

        if self.advantage is not None:
            _ensure_finite(float(self.advantage), "trajectory advantage")

    def to_policy_step_samples(self) -> List[PolicyStepSample]:
        if self.advantage is None:
            raise ValueError(
                "Trajectory advantage must be computed before creating training samples."
            )

        samples: List[PolicyStepSample] = []
        for action in self.actions:
            if not action.generated_token_ids:
                continue

            action.validate(require_old_log_probs=True)

            sample = PolicyStepSample(
                trajectory_id=self.trajectory_id,
                question_id=self.question_id,
                group_index=self.group_index,
                step_id=action.step_id,
                prompt_input_ids=list(action.prompt_input_ids),
                prompt_attention_mask=list(action.prompt_attention_mask),
                target_token_ids=list(action.generated_token_ids),
                target_token_mask=list(action.action_token_mask),
                old_log_probs=list(action.old_log_probs),
                advantage=float(self.advantage),
                trajectory_reward=float(self.reward.total),
                metadata={
                    "action_name": action.action_name,
                    "parse_success": action.parse_success,
                    "fallback_used": action.fallback_used,
                    "forced_stop": action.forced_stop,
                },
            )
            sample.validate()
            samples.append(sample)

        return samples

    def to_dict(self) -> Dict[str, Any]:
        self.validate(require_old_log_probs=False)
        return _to_plain(self)

    def to_json(self, indent: Optional[int] = 2) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent)


@dataclass
class RolloutGroup:
    question_id: str
    question: str
    trajectories: List[RolloutTrajectory] = field(default_factory=list)

    reward_mean: Optional[float] = None
    reward_std: Optional[float] = None
    zero_variance: Optional[bool] = None
    epsilon: float = 1e-4

    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def group_size(self) -> int:
        return len(self.trajectories)

    def add_trajectory(self, trajectory: RolloutTrajectory) -> None:
        if trajectory.question_id != self.question_id:
            raise ValueError(
                "All trajectories in a group must share the same question_id."
            )
        if trajectory.group_index != len(self.trajectories):
            raise ValueError(
                "group_index must equal the insertion position within the group: "
                f"expected {len(self.trajectories)}, got {trajectory.group_index}."
            )
        self.trajectories.append(trajectory)

    def compute_advantages(
        self,
        epsilon: Optional[float] = None,
        zero_variance_threshold: float = 1e-8,
        use_sample_std: bool = False,
    ) -> List[float]:
        if not self.trajectories:
            raise ValueError("Cannot compute advantages for an empty group.")

        eps = self.epsilon if epsilon is None else float(epsilon)
        if eps <= 0:
            raise ValueError(f"epsilon must be > 0, got {eps}.")

        rewards = [float(traj.reward.total) for traj in self.trajectories]
        for index, reward in enumerate(rewards):
            _ensure_finite(reward, f"trajectory reward[{index}]")

        mean = sum(rewards) / len(rewards)
        squared_error_sum = sum((reward - mean) ** 2 for reward in rewards)

        if use_sample_std and len(rewards) > 1:
            variance = squared_error_sum / (len(rewards) - 1)
        else:
            variance = squared_error_sum / len(rewards)

        std = math.sqrt(max(variance, 0.0))
        zero_variance = std <= zero_variance_threshold

        if zero_variance:
            advantages = [0.0] * len(rewards)
        else:
            advantages = [(reward - mean) / (std + eps) for reward in rewards]

        self.reward_mean = float(mean)
        self.reward_std = float(std)
        self.zero_variance = bool(zero_variance)
        self.epsilon = eps

        for trajectory, advantage in zip(
            self.trajectories, advantages, strict=True
        ):
            trajectory.advantage = float(advantage)

        return advantages

    def validate(self, require_old_log_probs: bool = False) -> None:
        if not self.question_id.strip():
            raise ValueError("question_id must be non-empty.")
        if not self.question.strip():
            raise ValueError("question must be non-empty.")

        seen_ids = set()
        for expected_index, trajectory in enumerate(self.trajectories):
            if trajectory.question_id != self.question_id:
                raise ValueError(
                    "Every trajectory must have the same question_id as its group."
                )
            if trajectory.group_index != expected_index:
                raise ValueError(
                    "Trajectory group indices must be contiguous and start at zero."
                )
            if trajectory.trajectory_id in seen_ids:
                raise ValueError(
                    f"Duplicate trajectory_id: {trajectory.trajectory_id!r}."
                )
            seen_ids.add(trajectory.trajectory_id)
            trajectory.validate(
                require_old_log_probs=require_old_log_probs
            )

        if self.reward_mean is not None:
            _ensure_finite(float(self.reward_mean), "reward_mean")
        if self.reward_std is not None:
            _ensure_finite(float(self.reward_std), "reward_std")

    def to_policy_step_samples(self) -> List[PolicyStepSample]:
        if any(trajectory.advantage is None for trajectory in self.trajectories):
            self.compute_advantages()

        samples: List[PolicyStepSample] = []
        for trajectory in self.trajectories:
            samples.extend(trajectory.to_policy_step_samples())
        return samples

    def to_dict(self) -> Dict[str, Any]:
        self.validate(require_old_log_probs=False)
        return _to_plain(self)

    def to_json(self, indent: Optional[int] = 2) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent)

    def save_json(self, path: str | Path, indent: int = 2) -> None:
        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            self.to_json(indent=indent),
            encoding="utf-8",
        )


def save_rollout_groups_jsonl(
    path: str | Path,
    groups: Sequence[RolloutGroup],
) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as handle:
        for group in groups:
            handle.write(
                json.dumps(group.to_dict(), ensure_ascii=False) + "\n"
            )
